services:
  mobile-app:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/opt/frontend-mobile-app
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 8081:8081
    command: ['npx', 'expo', 'start', '-c']
    env_file:
      - path: .env
        required: true
