FROM node:22-bullseye

# set our node environment, either development or production
# defaults to production, compose overrides this to development on build and run
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

# default to port 19006 for node, and 19001 and 19002 (tests) for debug
ARG PORT=19006
ENV PORT=$PORT
EXPOSE 8081 19006 19001 19002

#install global packages
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
RUN npm i --unsafe-perm -g npm@latest expo-cli exp
# Install required packages
RUN apt-get update && apt-get install -y qemu-user-static watchman
#We need to install this inorder to start a tunnel on the docker conatiner
RUN yarn add @expo/ngrok

# install dependencies first, in a different location for easier app bind mounting for local development
# due to default /opt permissions we have to create the dir with root and change perms
RUN mkdir /opt/frontend-mobile-app && chown root:root /opt/frontend-mobile-app
WORKDIR /opt/frontend-mobile-app
ENV PATH=/opt/frontend-mobile-app/.bin:$PATH
USER root
COPY package.json package-lock.json ./
RUN npm install

WORKDIR /opt/frontend-mobile-app
COPY . /opt/frontend-mobile-app

USER node